[package]
name = "pelite-cli"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"

license = "MIT"
authors = ["Casper <CasualX@users.noreply.github.com>"]
description = "Command-line tools for inspecting PE binaries with pelite"
categories = ["command-line-utilities"]

[dependencies]
basenc = "1.0.0-alpha.2"
clap = "4.6.7"
iced-x86 = { version = "1.21.0", default-features = false, features = ["decoder", "intel", "std"] }
md5 = "0.8.1"
pelite = { path = "..", features = ["basenc", "serde", "mmap"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11"
urandom = "1.0.0-alpha.3"
